package pipeline;

public enum CommandType {
    GET_QUANTITY,
    REDUCE_QUANTITY,
    ADD_QUANTITY,
    ADD_GROUP,
    ADD_PRODUCT_TO_GROUP,
    SET_PRICE,

    CREATE_PRODUCT,
    READ_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    SEARCH_PRODUCTS
}